<a href="https://colab.research.google.com/github/kipkii/Big_Wave/blob/main/4%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***`안녕하세요`***

1.   항목 추가

1.   항목 추가

*   항목 추가

---

\\:
*   항목 추가


2.   항목 추가


2.   항목 추가


## 안녕하세요
### 안녕하세요
#### 안녕하세요
##### 안녕하세요
**안녕하세요**
*안녕하세요*
_안녕하세요_
~~안녕하세요~~
>안녕하세요
* 안녕하세요
- 안녕하세요
[한빛미디어](https://www.hanbit.co.kr/)

![한빛미디어](https://cdn-prod.hanbit.co.kr/images/store/logo_hanbit_plus.png)

$ y=x /times z$

In [ ]:
print("hello World")

hello World

In [ ]:
seconds_in_a_week = 24*60*60*7
seconds_in_a_week

604800

In [ ]:
## 파이썬 라이브러리 이용해서 데이터 다운!

import gdown
gdown.download('https://bit.ly/3eecMKZ',
               '남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

Downloading...
From: https://bit.ly/3eecMKZ
To: /content/남산도서관 장서 대출목록 (2021년 04월).csv
100%|██████████| 58.1M/58.1M [00:00<00:00, 237MB/s]

'남산도서관 장서 대출목록 (2021년 04월).csv'

In [ ]:
### 인코딩 형식 지정해주어서 읽어오기

with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding = 'euc-kr' ) as f:
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

In [ ]:
## 인코딩 형식확인

import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv' , mode = 'rb') as f:
  d = f.readline()
print(chardet.detect(d))

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [ ]:
import os
import glob
import unicodedata

## NFC 방식 - 한글을 유니코드로 표현할 때 글자 단위로 저장

for filename in glob.glob('*.csv'):
  nfc_filename = unicodedata.normalize('NFC', filename)
  os.rename(filename, nfc_filename)

In [ ]:
import pandas as pd

In [ ]:
##  read_csv 함수 이용해서 데이터 프레임 만들기, 인코딩 형식 정해주

df = pd.read_csv("/content/남산도서관 장서 대출목록 (2021년 04월).csv", encoding = 'euc-kr')

/tmp/ipykernel_4633/3083690639.py:1: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/남산도서관 장서 대출목록 (2021년 04월).csv", encoding = 'euc-kr')

In [ ]:
## low_momeory 옵션추가 , CSV 파일은 텍스트 파일이라 각 열이 숫자형인지, 문자열인지에 대한 정보가 없음 Pandas는 데이터를 읽을 때 각 열의 데이터 타입을 스스로 추측해야함.
## low_memory=False:
## 파일 전체를 한 번에 메모리에 올린 후 타입을 추측 메모리는 많이 사용하지만, 전체 데이터를 보고 타입을 결정하므로 훨씬 정확하고 경고가 발생하지 않는다는 특징

df = pd.read_csv("/content/남산도서관 장서 대출목록 (2021년 04월).csv", encoding = 'euc-kr', low_memory=False)

In [ ]:
## 데이터프레임이 정상적으로 생성되었는지 확인
## pandas head()를 사용해서 상위 n개확인 () 가 공란일 경우 기본 5개 조회가능

df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [ ]:
## 인코딩 방식, 컬럼 별로 dtype 지정해서 불러오기

df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr',
                 dtype={'ISBN': str, '세트 ISBN': str, '주제분류번호': str})
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [ ]:
## 완성된 데이터 프레임을 csv형식으로 저장
df.to_csv('ns_202104.csv')

In [ ]:
## 인덱스 3번쨰 까지반 반복해서읽어오

with open('ns_202104.csv') as f:
    for i in range(3):
        print(f.readline(), end='')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [ ]:
+## low_m+omory로 한번에 데이터타입 추측(false니까 한번에)
## index_col = 0 첫번째 0번열을 이름으로 지정하겠다.
ns_df = pd.read_csv('ns_202104.csv', index_col=0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

###파이썬 객체를 JSON 문자열로 변환하기: json.dumps( ) 함수

In [ ]:
import json

In [ ]:
d = {"name" : "혼자 공부하는 데이터 분석" }
print(d['name'])

혼자 공부하는 데이터 분석

In [ ]:
d_str = json.dumps(d, ensure_ascii=False)
print(d['name'])

혼자 공부하는 데이터 분석

In [ ]:
print(type(d_str))

<class 'str'>

###JSON 문자열을 파이썬 객체로 변환하기: json.loads( ) 함수

In [ ]:
d2 = json.loads(d_str)
print(d2['name'])

print(type(d2))

혼자 공부하는 데이터 분석
<class 'dict'>

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')

print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선","홍길동"], "year": 2022}')

print(d3['name'])
print(d3['author'][1])
print(d3['year'])

혼자 공부하는 데이터 분석
홍길동
2022

In [ ]:
d4_str = """
[
  {"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022},
  {"name": "혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year": 20}
]
"""

d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

###JSON 문자열을 데이터프레임으로 변환하기: read_json( ) 함수

In [ ]:
import pandas as pd
pd.read_json(d4_str)

/tmp/ipykernel_1167/1308304786.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(d4_str)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선    20

In [ ]:
pd.DataFrame(d4)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선    20

###XML 문자열을 파이썬 객체로 변환하기: fromstring( ) 함수

In [ ]:
x_str = """
<book>
  <name>혼자 공부하는 데이터 분석 </name>
  <author>박해선</author>
  <year>2022</year>
</book>
"""

In [ ]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

In [ ]:
print(book)
print(type(book))
print(book.tag)

<Element 'book' at 0x7ea014e7fbf0>
<class 'xml.etree.ElementTree.Element'>
book

###자식 엘리먼트 확인하기: findtext( ) 메서드

In [ ]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x7ea014e7c9a0>, <Element 'author' at 0x7ea014e7fa10>, <Element 'year' at 0x7ea014e7fec0>]

In [ ]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 데이터 분석
박해선
2022

In [ ]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')

print(name)
print(author)
print(year)

혼자 공부하는 데이터 분석
박해선
2022

In [ ]:
x2_str = """
<books>

  <book>
    <name>혼자 공부하는 데이터 분석 </name>
    <author>박해선</author>
    <year>2022</year>
  </book>

  <book>
    <name>혼자 공부하는 머신러닝+딥러닝 </name>
    <author>박해선</author>
    <year>2020</year>
  </book>

</books>
"""

In [ ]:
## fromstring() 이용해 부모 엘리먼트 확인하기
import xml.etree.ElementTree as e

books = et.fromstring(x2_str)
print(books.tag)

books

In [ ]:
## 여러 개의 자식 엘리먼트 확인하기: findall( ) 메서드와 for 문
## 동일 이름의 여러자식 노드 찾을떄는 findall() 메서드,for문 같이 사용

for book in books.findall('book'):
  name = book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')

  print(name)
  print(author)
  print(year)
  print()

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 머신러닝+딥러닝
박해선
2020

In [ ]:
import pandas as pd

pd.read_xml(x2_str)

/tmp/ipykernel_1167/1172478832.py:3: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(x2_str)

                name author  year
0    혼자 공부하는 데이터 분석     박해선  2022
1  혼자 공부하는 머신러닝+딥러닝     박해선  2020

In [ ]:
import requests

url = "http://data4library.kr/api/loanItemSrch?format=json&startDt=2021-04-01&endDt=2021-04-30&age=20&authKey=53f99b708e70f661573b68aaf9d2f34de8bda1579554d3d588ad78f783042fde"

r = requests.get(url)

In [ ]:
data = r.json()
print(data)

{'response': {'error': 'API 활성화 상태가아닙니다.'}}